name: Zach Tratar
description: Ramblings on startups, design, engineering, and political philosophy.
url: http://zachtratar.com

safe:        false
auto:        false
port: 4000
baseurl:    /
url: http://zachtratar.com

source:      .
destination: ./_site
plugins_dir:     ./_plugins

collections_dir: collections
collections:
  posts:
    output: true
  projects:
    output: true

future:      true
lsi:         false
highlighter: false
markdown:    kramdown
permalink:   /:title.html

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style

asset_bundler:
  compress:
    js: closure
    css: false
  base_path: /bundles/
  server_url:
  remove_bundled: true
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"
